apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafeweb
spec:
  template:
    spec:
      containers:
      - name: cafeweb
        image: sreedocker123/mompopcafeapp:v1  Replace with the appropriate image tag or use a placeholder
  replicas: 3  # Replace with the appropriate replica count or use a placeholder
