Flag --validation has been deprecated, this arg is no longer used, all resources are validated using server-side apply dry-run
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: my-app-prod
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./Deploy/kustomize_cafe_app/overlays/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-app-repo
  targetNamespace: prod
