replicaCount: 1

mysql:
  image: sreedocker123/mompopcafedb:v1
  database: mom_pop_db
  user: root

cafeweb:
  image: sreedocker123/mompopcafeapp
  tag: v1

persistentVolume:
  size: 10Gi
  hostPath: "/mnt/data/dev"

config:
  showServerInfo: "false"
  timeZone: "America/New_York"
  currency: "$"
  db_url: "10.32.0.8"
  db_name: "mom_pop_db"
  db_user: "root"
  db_password: "Msois@123"

